name: make gcc for kylin
on:
  workflow_dispatch:
    inputs:
      gccv:
        description: 'gcc version'
        default: '11.5.0'
        required: false
        type: string
      osv:
        description: 'kylin version'
        default: '10sp3'
        required: false
        type: string

jobs:
  compile:
    strategy:
      matrix:
        platform: ["amd64", "arm64"]
        # platform: ["amd64"]
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Prepare gcc src
      run: |
        curl -L -O https://mirrors.ustc.edu.cn/gnu/gcc/gcc-${{ inputs.gccv }}/gcc-${{ inputs.gccv }}.tar.gz
        tar -xzf gcc-${{ inputs.gccv }}.tar.gz
      working-directory: /tmp
    - name: make gcc
      run: |
        mkdir gcc-build gcc-output
        docker run --platform linux/${{ matrix.platform }} --rm -v /tmp:/workspace -w /workspace djangoyi/gcc-compiler:${{ inputs.osv }} bash -c "cd /workspace/gcc-build && ../gcc-${{ inputs.gccv }}/configure --disable-multilib && make && DESTDIR=/workspace/gcc-output make install"
      working-directory: /tmp
    - name: pack binaries
      run: |
        tar -czf /tmp/gcc-${{ inputs.gccv }}-${{ matrix.platform }}.tgz /tmp/gcc-output/*
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kylin-${{ matrix.platform }}
        path: /tmp/gcc-${{ inputs.gccv }}-${{ matrix.platform }}.tgz

  release:
    runs-on: ubuntu-latest
    needs: compile
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # - name: Remove release
    #   uses: liudonghua123/delete-release-action@v1
    #   with:
    #     release_name: redis-${{ inputs.redisv }}_ubuntu-${{ inputs.osv }}
    #     suppress_errors: true
    # - name: Remove tag
    #   run: |
    #     git tag -d mongo-${{ needs.export.outputs.mongo }}_ubuntu-${{ needs.export.outputs.ubuntu }} || :
    #     git push origin --delete mongo-${{ needs.export.outputs.mongo }}_ubuntu-${{ needs.export.outputs.ubuntu }} || :
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        pattern: kylin-*
        path: release
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/kylin-*/*
        tag_name: gcc-${{ inputs.gccv }}_kylin-${{ inputs.osv }}